### ISSUE TITLE
MLSys '20 | Blink: Fast and Generic Collectives for Distributed ML

### ISSUE THREAD

**Issue by zhongyuchen** [zhongyuchen/read-papers#17]
https://arxiv.org/pdf/1910.04940.pdf

看上去是做了个比NCCL快8倍的通信库，有点NB

**Comment by GuanhuaWang** [comment]
Yes, we achieve near-optimal AllReduce performance by using automatic generated spanning trees, instead of NCCL/Horovod/Baidu Ring-AllReduce.

**Comment by zhongyuchen** [comment]
非常有意思的一篇文章，看的十分过瘾.

文章首先批判了一下现有的NCCL库，指出其没有考虑topology heterogeneity. 然后指出忽略topology heterogeneity会有严重问题，因为: 
1. 可能分配的GPUs无法形成一个NVLink环，导致走PCIe，造成严重性能瓶颈. 
2. 即便能够形成一个NVLink环，也可能导致无法全部利用所有link，导致under-utilization. 

另外GPU cluster的scheduler一般不知道机器内部GPU的topology，所以上述两个问题是工业界的顽疾.

作者接着批判了NCCL使用ring-based scheme的弊端，指出每个节点只有一进一出，无法适应复杂的拓扑结构，并且可能导致有些link没用上.

![image](https://user-images.githubusercontent.com/25879526/74587954-7bdf3000-5033-11ea-87ab-aaa759b3d176.png)
(图为DGX-1 GPU拓扑结构，用`nvidia-smi topo -m`可以查看)

因此，作者考虑能否打破ring-based方法呢?作者开始考虑能否使用packing spanning tree. 为此作者做了两个实验(micro benchmarks)来验证是否可行.

1. depth test: 验证随着深度增加，GPU with NVLink能够很好reduce-forward数据.
2. multi-transfer test: 验证一个GPU是否能同时传输数据. 测了两种模式: MIMO(multi-input multi-output) 和MCA(multi-chain aggregation). 结果表明是可以的，throughput损失很少.

![image](https://user-images.githubusercontent.com/25879526/74588116-d4fb9380-5034-11ea-8a43-5cf2a4d69c3e.png)

这些结果就为使用packing spanning tree铺平了道路. 

接着作者开始介绍Blink的workflow. 

![image](https://user-images.githubusercontent.com/25879526/74588142-01afab00-5035-11ea-97fa-4ce2fd1e83f3.png)

检测topo -> 生成Tree -> 生成代码 -> libblink.so -> 动态链接到主程序

这里有一个trick: 通过设置`LD_PRELOAD`环境变量来覆盖libnccl.so，优先使用其实现的版本. 由于生成代码会和NCCL代码接口一样，所以无需修改用户代码. 

## TODO

**Comment by zhongyuchen** [comment]
为了看后面部分补了一下图论的知识....

edge-disjoint: 不共享任何edge

arborescence: branching, rooted directed spanning tree

> An arborescence packing is the maximum number of arborescences A1, A2, . . . Ak such that all are edge disjoint. They all share the same root.

Edmond’s Theorem: The maximum number of arborescences k is equal to the minimum cut. (当各边容量都为1时)

看上去有点像最大流最小割定理的特殊情况，当各边容量为1时，即求割边数量最小. 

## references 

1. https://courses.cs.washington.edu/courses/cse522/04au/notes/lect15.pdf

**Comment by zhongyuchen** [comment]
## 系统设计

先考虑简单的broadcast情况，问题其实是单源多汇，即一个源点，其余节点都是汇点，求最大流量.
作者说这个问题已经被研究过了，等同于这样一个问题: 

![image](https://user-images.githubusercontent.com/25879526/74628031-7e569c80-518f-11ea-89e8-f176b9676d79.png)

> More formally, our problem statement is given a graph G with vertices V , edges E and root vertex r and spanning trees T 1 , T 2 , T 3 ...T i we wish to find the weights w i such that the sum of weights trees passing through any edge does not exceed the capacity of the particular edge.

**这里我有一个疑问: 按理来讲可以构造一个超级汇点，然后跑一个最大流?**

作者说这个问题很难解，不过好像也不是NP难的，文中也提到有人给出了多项式解法. O(n^3 mlog(n^2 /m)). (节点数n，边数m) 然后作者用了一个叫做MWU的算法来求解. 算法复杂度降到了O(m ln m/ε^2 ) 在(1-ε)近似的情况下. 看上去还和节点数n无关. 

这个算法很简单，每轮迭代先找一个MST，然后在这树所在的边的权值加上ε%.  直到无法满足容量的条件，迭代结束. 这样就得到了T1 T2 T3 .... T i和对应的w1 w2 w3 .... wi. \sum wi 就是最大容量. 

然后又发现这个算法产生的树可能会很多，太多树会导致每棵树传输的数据量太少了，导致低效率. 所以下一步考虑怎么减少产生的树. 他们的办法是再跑一遍，不过这次是跑ILP，即固定w必须是整数，然后限定树的数目不超过之前得到的k个. 

接着考虑multi-to-multi的情况. 作者说其实已经解决了，因为链路本身就是双向的，所以只需要同时跑一个multi-to-one和一个one-to-multi就行了. 比如AllReduce = Reduce + Broadcast. 同时在一棵树但相反方向做. 这样做和allreduce的最小开销是一样的，都是2 (N-1) / N. 

然后考虑hybrid传输，作者说原生cuda好像不支持，只能搞两套树，一套disable nvlink只跑pcie，另一套正常跑nvlink. 根据带宽分配数据量. 

最后提了下扩展到DGX-2和分布式. DGX-2有16个V100，俩个NVSwitch，具体topo不了解. 网上只找到个不清楚的图. 分布式的情况很简单，就是先做local reduce，然后走网络传输，最后local broadcast. 

![image](https://user-images.githubusercontent.com/25879526/74631692-89fa9100-5198-11ea-972e-4f2a1d78b814.png)

**Comment by zhongyuchen** [comment]
## 实现

最好奇的部分还是code gen，我之前想难不成搞了个编译器? 看了下实现发现其实是根据tree组装下各个CUDA API.  

作者介绍了broadcast和allreduce的codegen实现:
1. broadcast: 每个tree调`cudaMemCpy`，然后分成chunks以减少latency，每个chunk传完了用cudaEvent通知. 不同tree的并行使用了cudaStream. 
2. allreduce: 上面说了，就是broadcast + reduce同时反向做. 

*话说分chunks也有调用`cudaMemCpy` kernel的overhead吧?*

接着讨论了下codeGen的优化. 

先补充说明了为什么要分chunks. 因为CUDA给的API好像不能pipeline，所以必须等传完才能继续forward...*CUDA真垃圾，逃（*. 然后提到了我刚才想到的overhead. 所以的确需要一个trade-off. 这个问题他们用了一个叫做MIAD的办法解决(或者说优化)...就是慢慢加chunk size，如果throughput也增加，继续加，如果throughput下降，那么chunk size下降.... 这大概就是梯度上升的initilize w=0的版本....能这么做，是因为这个throughput跟chunk size的关系，很可能就差不多是个先增后减的关系. 

最后是link sharing. 主要是解决fair sharing的问题. 重复使用cudaStream. 看上去是共享路径才用同一个cudaStream. 其他不重叠的还是单独开cudaStream. 

typos: 
1. P8 4.1 broadcast L4  "note" -> "node"

**Comment by zhongyuchen** [comment]
最后是实验

对于broadcast和allreduce，8块GPU所有组合都做了一遍. 看上去除了0-7全用，其他都有正收益. 不知道为什么8卡全用反而会慢一些? 

hybrid也做了对比实验证明确实有点收益.

最后跑了实际的训练任务. 可惜只有vision的模型，没跑transformer-based模型. 还试了跨卡同步，主要是削减了intra-node时间，inter-node是还是瓶颈. 

___

NCCL的ring base的条件还是太苛刻了，很难搞出一个ring，ring是一个比较特殊的形状. 实际中还是用tree用graph比较general. 本文出发点就是如此. 自然会想到推广到分布式场景. 我觉得可以一试. 云场景中，买的服务器很可能不是正好形成一个圈的. 它们之间的连接可能也就是一个任意的图......感觉需要去了解下云计算是怎么分配虚拟机器的.

**Comment by jiangxiaobin96** [comment]
请问Blink开源了吗

**Comment by vycezhong** [comment]
> 请问Blink开源了吗

你好，我也不清楚诶

**Comment by jiangxiaobin96** [comment]
你好，我阅读完论文有一些地方不能理解
> 这个算法很简单，每轮迭代先找一个MST，然后在这树所在的边的权值加上ε%. 直到无法满足容量的条件，迭代结束. 这样就得到了T1 T2 T3 .... T i和对应的w1 w2 w3 .... wi. \sum wi 就是最大容量.
> Q：这里它为什么需要在边的权值上加上ε%，然后生成多个MST？

> Once we receive the input buffer to be broadcast from the root node, we split the buffer among all the spanning trees based on their weights.
> Q：这里如果按照流水线的理解，收到从root广播来的数据应该会继续把这一个小chunk传递下去，这句话就不知道它想干什么了？

**Comment by vycezhong** [comment]
@jiangxiaobin96  你好. 

Q1：这里它为什么需要在边的权值上加上ε%，然后生成多个MST？

MWU这个算法应该就是这么做的. 具体为啥这么做我也不清楚.

Q2：这里如果按照流水线的理解，收到从root广播来的数据应该会继续把这一个小chunk传递下去，这句话就不知道它想干什么了？

他这里说的input buffer我感觉是指在root node上的?
