### ISSUE TITLE
arXiv '19 | ZeRO: Memory Optimization Towards Training A Trillion Parameter Models

### ISSUE THREAD

**Issue by zhongyuchen** [zhongyuchen/read-papers#28]
https://arxiv.org/pdf/1910.02054

上来说data parallelism不够memory efficiency，model parallelism不够scaling efficiency. ZeRO能够两者都efficient.... 看具体文章才知道怎么做的

Turing-NLG基于这个训练

**Comment by zhongyuchen** [comment]
idea超棒的. 我吹爆. data parallelism从此可以横着走了，吊打model parallelism. 

但文章写的太烂了，估计是临时赶出来的，废话一箩筐，一句话重复三遍. 中间推导communication压根不推. 多几个流程图会好很多. 希望作者重新写遍投个好点的会议... 

文章的出发点是data parallelism虽然scaling efficient但是非常浪费显存，因为每个device都需要存一个replica. 而model parallelism虽然可以允许切割模型，但是带来的通信overhead过于大... 本文提出一种办法，可以让data parallelism的每张卡的显存占用降低到O(1/N_d).... N是数据并行度，即可以理解多少个FP/BP同时在做. 通常对于data parallelism，N_d = 卡的个数.

首先要考虑memory footprint都是哪些，假设model有\phi个parameters，比如BERT(0.3B), GPT(1.5B)，那么:
1. parameters: 如果用FP16存储，那么需要 2\phi bytes
2. gradients: 如果用parameters使用FP16，那么gradients也需要 2\phi bytes
3. optimizer states: 如果使用Adam做mix-precision，需要保存FP32的parameters和optimizer states(momentum + variance)，带来了4\phi + 8\phi = 12\phi的存储空间. 

所以对于一个参数量为\phi的模型，需要2 + 2 + 12 = 16\phi的空间. 比如GPT的1.5B，本来2\phi差不多是3GB. 现在16\phi需要24GB了 >> 16GB.  
```
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/THC/generic/THCStorage.cu:66
```

文章的想法很简单，就是把memory footprint做partition，分成N_d块到各个devices. 但这样怎么训练啊，不是变成和model parallel一样了? 他们没走model parallel的老路，而是另辟蹊径. 中间communication还是parameters/gradients而不是activations. 

具体流程:

1. Forward Propagation(FP)：由于每个device只有自己的partition，要做FP，必须要做all-gather. 但直接做all-gather导致每个device都需要存\phi而不是\phi/N_d了. 他们把all-gather做成了pipeline式，也就是某个device在需要某层的parameters之前，其他partition应该把parameters broadcast过去. 这样用完了某曾的parameters就可以丢掉. 所以，总的来看，memory footprint基本还是\phi/N_d. 

所以FP的通信开销为\phi. 

2. Back Propagation(BP)：做BP的时候需要parameters，同样也是通过其他partition broadcast的方法，所以通信开销也是\phi. 比如计算最后一层的梯度，首先需要接受其他partition broadcast的最后一层参数，然后计算梯度，计算完后，一方面向上一层传递，一方面把梯度传给对应的保存这个参数对应梯度的device出去，其实就是reduce-scatter. 

首先和FP一样需要broadcast parameters，所以通信开销需要\phi. 同时需要reduce-scatter gradients，通信开销也是\phi. 

**所以总体来看，通信开销为3\phi. 只是传统的data parallel的2\phi 1.5倍而已.**

这其实就是一个trade-off,用通信换空间. 其实我觉得如果一张卡能装下整个model的话，直接data parallel就行了. 他这里想搞一个超级巨大的模型，又不喜欢model parallel，才搞出这样一个法子. 

___

现在还是all-reduce式. 能不能搞成ps那种架构?

**Comment by zhongyuchen** [comment]
文章好像是all-reduce架构的，感觉用ps架构在调度上更简洁一点. 比如FP/BP的时候只需要分层PULL parameters，而不是调度其他worker来broadcast. BP算完每层grad就PUSH，而不是reduce到对应的worker那里去. 反正server上的参数又不用放到显存里面，理论上模型也可也无穷大.

应该是可行的，看有空能不能整合进byteps（逃

**Comment by vycezhong** [comment]
比如一个model有很多layers，我把它们分成4块，每一块占用一个GPU. 这和PP的placement一模一样. 究竟谁更快呢？不知道. 

I vote for PP.
