### ISSUE TITLE
AISTATS '17 | Communication-Efficient Learning of Deep Networks from Decentralized Data

### ISSUE THREAD

**Issue by zhongyuchen** [zhongyuchen/read-papers#33]
https://arxiv.org/pdf/1602.05629.pdf

一开始我以为是异步，结果发现是同步....不过是delayed同步.

**Comment by zhongyuchen** [comment]
federated learning其实算是异步分布式训练的一个特殊分支. 以前的训练都是在cluster/data center做的，有丰富的G

**Comment by zhongyuchen** [comment]
隐私问题也不一定非要federated learning这样. 也可以考虑把用户数据加密传输到云端. 最简单的就是hash一下. 云端就干脆都用hash值作为输入去训练. 反正别人根据hash值是不可能反推的. 再用加密传输避免别人用hash值直接去训练. 这叫hash learning. 总之我觉得不一定非要on device learning.

**Comment by vycezhong** [comment]
federated learning是可以双向传输$\Delta w$的，但$\Delta w$不是简单但gradient，而是累加的gradients

**Comment by vycezhong** [comment]
FedAvg就是local sgd. 同出异名.
